### ISSUE TITLE
problem with cc65 when building

### ISSUE THREAD

**Issue by RK33DV** [cppchriscpp/nes-starter-kit#27]
whenever i try to bulid my game i get this error:

make: ./tools/cc65/bin/ca65: No such file or directory

i have cygwin, make, and cc65 installed (with a Environment variable) 

im using windows 10 if that helps

**Comment by cppchriscpp** [comment]
Hello! Thank you for your interest in this project.

It sounds like you're really close. I think you'll need to download the [tool zip](https://devnull.nes.science/nes_starter_kit_tools.zip) and extract it over the tools folder of your game. It should prompt you if it's okay to replace the tools folder - give it permission and it will merge your existing tools folder with the required tools, including cc65. 

Feel free to reach back out if that doesn't solve it! If you really want to use your installed copy of cc65 I can walk through that, though I don't actively support it. (it's a few lines to change in the makefile)

**Comment by RK33DV** [comment]
IT WORKED :D thanks man

**Comment by cppchriscpp** [comment]
Glad to hear it! Thanks for following up to let me know
